version: '3.6'

services:
  
  sqldata:
    build:
      context: .
      dockerfile: Db/Dockerfile
    ports:
      - "1450:1433"
    environment:
      SA_PASSWORD: "a12345678?"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
  
  todo-minimal-api:
    image: ${DOCKER_REGISTRY-}todo-minimal:1.0.0
    build:
      context: .
      dockerfile: Todo.Api/Dockerfile
    environment:
      - "ConnectionStrings:ConnectionString=Server=sqldata;Database=TodoMinimal;User ID=sa;Password=a12345678?"     
    ports:
      - "8081:80"
    depends_on:
      - sqldata


volumes:
  sqlserver_data: