version: '3.9'

services:
  todo-minimal-api:
    image: ${DOCKER_REGISTRY-}todo-minimal:1.0.0
    build:
      context: .
      dockerfile: Todo.Api/Dockerfile
    environment:
      - "ConnectionStrings:ConnectionString=Server=sqldata;Database=TodoMinimal;User ID=sa;Password=a12345678?"     
    ports:
      - "8081:80"
    depends_on:
      - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "a12345678?"
      ACCEPT_EULA: "Y"
    volumes:
      - /home/andre/DB/mssql:/var/opt/mssql/data
    ports:
      - "1450:1433"